---

- name: Check if the file exists
  become: false
  ansible.builtin.stat:
    path: "{{ agd_absolute_project_path }}/{{ agd_relative_src_path }}"
  register: file_stat
  delegate_to: localhost

- ansible.builtin.debug:
    msg: "Failed to find files in: {{ agd_absolute_project_path }}/{{ agd_relative_src_path }} ... [skipping following tasks]"
  when: not file_stat.stat.exists

- name: Combine Git URL and relative path
  ansible.builtin.set_fact:
    git_archive:
      '{{ agd_relative_src_path | git_download_url(agd_absolute_project_path,
      agd_git_token) }}'
    temp_id:
      "{{ query('community.general.random_string',
      override_all='0123456789ABCDEF') | first }}"
  delegate_to: localhost

- name: Set component-strip
  ansible.builtin.set_fact:
    components_strip: "{{ git_archive.length - 1 if agd_download_mode == 'directory' else git_archive.length }}"

- name: Asyncronous download Files from git
  become: true
  ansible.builtin.shell: |
    mkdir -p {{ agd_data_dest }} &&
    wget -O /tmp/tmp_{{ temp_id }}.tar.gz {{ git_archive.url }} &&
    tar -xvf /tmp/tmp_{{ temp_id }}.tar.gz --strip-components={{ components_strip }} -C {{ agd_data_dest }}/ &&
    chown {{ agd_owner }}:{{ agd_group }} {{ agd_data_dest }}/ -R &&
    find {{ agd_data_dest }} -type f -exec chmod {{ agd_mode }} {} \; &&
    rm /tmp/tmp_{{ temp_id }}.tar.gz && history -c
  async: '{{ agd_timeout }}'
  poll: 0
